// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    onedollar: function(options) {
      var settings;

      settings = {
        score: 80
      };
      settings = $.extend(settings, options);
      return this.each(function() {});
    }
  });

}).call(this);
